# This is a basic workflow to help you get started with Actions

name: Arduino

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  - name: Compile arduino:
    runs-on: ubuntu-latest
    uses: arduino/setup-arduéino-cli@v1.0.0
    with:
    - uses: actions/checkout@master
    - run: |
        mkdir -p "$HOME/Arduino/libraries"
        ln -s "$PWD" "$HOME/Arduino/libraries/."
    - run: |
        arduino-cli core update-index
        arduino-cli core install arduino:avr@1.8.2
    - run: arduino-cli compile --fqbn arduino:avr:uno ./arduino/ArduinoPacketGenerator/ArduinoPacketGenerator.ino
